USE DCDbHive;
CREATE TABLE DevicesDataPar
(
    READINGDATETIME TIMESTAMP,
    VALUE DOUBLE
)
PARTITIONED BY ( 
  DEVICEID INT)
STORED AS ORC
TBLPROPERTIES ("ocr.compress"="SNAPPY");

INSERT INTO DevicesDataPar PARTITION(DEVICEID)
SELECT READINGDATETIME,VALUE,DEVICEID FROM DevicesDataExternal