CREATE TABLE [dbo].[ImageObjects]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[TimeStamp] DATETIME2(7) DEFAULT SYSDATETIME(),
	[FileName] VARCHAR(255) NOT NULL,
	[Object]  VARCHAR(255) NOT NULL,
	[Conf] FLOAT NOT NULL
)
