--time traveling zerocopy clonning
USE FPCLOUD;
USE WAREHOUSE MYLAB_DW;
USE ROLE SYSADMIN;
USE SCHEMA STAGE;

SELECT * FROM TRIPS LIMIT 100;

UPDATE TRIPS SET START_STATION_NAME='EMPTY';

SELECT DISTINCT START_STATION_NAME FROM TRIPS 

--UPDATE QUERY
SELECT * FROM TABLE (information_schema.query_history()) 
WHERE QUERY_TEXT LIKE 'UPDATE%EMPTY%' ORDER BY START_TIME DESC;

--copy query id
SELECT DISTINCT START_STATION_NAME FROM TRIPS  BEFORE(statement=>'018fc1fc-00e5-a299-0000-00001fad5209');

CREATE OR REPLACE TABLE TRIPS_RESTORED CLONE 
    TRIPS  BEFORE(statement=>'018fc1fc-00e5-a299-0000-00001fad5209');
    
SHOW TABLES

ALTER TABLE TRIPS_RESTORED SWAP WITH TRIPS;

SELECT DISTINCT START_STATION_NAME FROM TRIPS;

--DROP TEMP TABLE
DROP TABLE TRIPS 
SELECT DISTINCT START_STATION_NAME FROM TRIPS 

UNDROP TABLE TRIPS 

SELECT DISTINCT START_STATION_NAME FROM TRIPS 