CREATE TABLE [load].[DataLoadLog]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[TableId] INT NOT NULL,
	[LoadDate] DATETIME2(7) NOT NULL,
	[DataContainer] VARCHAR(1024) NOT NULL,
	[DataPath] VARCHAR(1024) NOT NULL,
	[DataFormat] VARCHAR(255) NOT NULL,
	[DataFormatOptions] VARCHAR(255) NOT NULL,
	[EltProc] INT NOT NULL
	CONSTRAINT [PK_DataLoadLog] PRIMARY KEY CLUSTERED (Id)
)