--time traveling zerocopy clonning
USE FPCLOUD;
USE WAREHOUSE MYLAB_DW;
USE ROLE SYSADMIN;
USE SCHEMA STAGE;

SELECT * FROM TRIPS LIMIT 100;

UPDATE TRIPS SET START_STATION_NAME='EMPTY';

SELECT DISTINCT START_STATION_NAME FROM TRIPS 

--UPDATE QUERY
SELECT * FROM TABLE (information_schema.query_history()) 
WHERE QUERY_TEXT LIKE 'UPDATE%EMPTY%' ORDER BY START_TIME DESC LIMIT 1;

--copy query id
SELECT DISTINCT START_STATION_NAME FROM TRIPS  BEFORE(statement=>'019286ed-006b-1a43-0000-2665000259ee');

CREATE OR REPLACE TABLE TRIPS_RESTORED CLONE 
    TRIPS  BEFORE(statement=>'019286ed-006b-1a43-0000-2665000259ee');
    
SHOW TABLES

SELECT DISTINCT START_STATION_NAME FROM TRIPS_RESTORED

ALTER TABLE TRIPS_RESTORED SWAP WITH TRIPS;

SELECT DISTINCT START_STATION_NAME FROM TRIPS;

--DROP TEMP TABLE
DROP TABLE TRIPS 
SELECT DISTINCT START_STATION_NAME FROM TRIPS 

UNDROP TABLE TRIPS 

SELECT DISTINCT START_STATION_NAME FROM TRIPS 